stages:
    - build
    - deploy

lintDebug:
    stage: build
    script:
    - chmod +x ./gradlew
    - ./gradlew lintDebug -Pci -PbuildDir=lint --console=plain
    tags:
        - lint-tag
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'

#publish:
#    stage: deploy
#    script:
#        - chmod +x ./gradlew
#        - ./gradlew clean -PbranchType=tag :core_datareport_plugin:moduleAarTask :core_datareport_plugin_interface:moduleAarTask
#    tags:
#        - publish-tag
#    rules:
#        - if: '$CI_COMMIT_TAG =~ /^v/'